# Generated by Django 5.2.2 on 2025-06-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLetter',
            fields=[
                ('letter_no', models.AutoField(primary_key=True, serialize=False)),
                ('letter_to', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_from', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('letter_notedby', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_recom_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('memo_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('memo_date', models.DateField()),
                ('memo_to', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_to_pos', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_thru', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_thru_pos', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_from', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_from_pos', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('memo_content', models.TextField(blank=True, null=True)),
                ('memo_recomm_by', models.CharField(blank=True, max_length=50, null=True)),
                ('memo_approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('memo_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MOAU',
            fields=[
                ('moau_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('notarized_by', models.CharField(blank=True, max_length=255, null=True)),
                ('notarized_date', models.DateField(blank=True, null=True)),
                ('moau_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOrder',
            fields=[
                ('so_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('so_date', models.DateField(blank=True, null=True)),
                ('so_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('so_content', models.TextField(blank=True, null=True)),
                ('so_for', models.IntegerField(blank=True, null=True)),
                ('so_signedby', models.CharField(blank=True, max_length=100, null=True)),
                ('so_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_no', models.CharField(max_length=10)),
                ('series_of', models.CharField(max_length=4)),
                ('date_issued', models.DateTimeField()),
                ('place', models.CharField(max_length=200)),
                ('inclusive_dates', models.CharField(blank=True, max_length=30, null=True)),
                ('mode_trans', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('approved_by', models.CharField(default='MA. CARLA A. OCHOTORENA, RN., Ph.D.', max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('to_no', 'series_of')},
            },
        ),
        migrations.CreateModel(
            name='MOAUParties',
            fields=[
                ('moauparties_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency', models.CharField(max_length=255)),
                ('represented_by', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('referred_to_as', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('moau_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.moau')),
            ],
            options={
                'unique_together': {('moau_no', 'agency')},
            },
        ),
        migrations.CreateModel(
            name='MOAUSignatories',
            fields=[
                ('mousgn_id', models.AutoField(primary_key=True, serialize=False)),
                ('signed_by', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('agency', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('moau_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.moau')),
            ],
            options={
                'unique_together': {('moau_no', 'signed_by')},
            },
        ),
    ]
